### ISSUE TITLE
Simplifying register functions

### ISSUE THREAD

**Issue by jrebecchi** [krypton-org/krypton-drafts#5]
For the system simplicity, a unique function will be provided for registration: `registerWithEmail` and `registerWithUsernameAndEmail` can be merged.

2 possible names:
- `registerWithEmail` - it would give the system the possibility to add other registration strategies in the future.
- `register` - more simple, but the API might be unclear in the future if we add new registration strategies.

Opinions?

**Comment by junekiwi** [comment]
I vote for `registerWithEmail`; leaves room for future improvements.

**Comment by jrebecchi** [comment]
Finally, I think that naming it `registerWithEmail` is not great. Indeed, it implies that registration is only with an email when it is actually with an email, password and the entire User Model that can be extended server-side with the `extendedSchema` property.

So how to name the login/registration methods in order to make it simple and extensible? 

I think we should distinguish login strategies and registration strategies.

**Possible login strategies:** 
- If we add other user providers with the OAuth protocol we could add new methods like `loginWithGoogle`, `loginWithFacebook`, `loginWithGithub`. Server-side those methods would imply the registration/login at the same time, as a kind of `findOrCreateUser`. There won't be any direct registration.

**Possible registration strategies:**
- The actual registration strategy is with an email and password implying a login with an email and password. We could imagine naming those methods `registerWithEmailAndPassword` and `loginWithEmailAndPassword`.
- If we add a password-less registration, only based on the email by sending to it a code or a validation link. We could imagine naming those methods `registerWithEmail` and `loginWithEmail`.

Finally I think `registerWithEmailAndPassword` and `loginWithEmailAndPassword` are too verbose.
As a simple solution we could name those standard authentication methods `register` and  `login`. The future login/registration strategies could have more made-up names to mark their difference.

- `register` -> register a user with email, password and the rest of the user model.
- `registerPasswordLess` -> register a user with an email and the rest of the user model (no password).

- `login` -> login with email and password
- `loginPasswordLess` -> login by sending an email to the user containing a validation link
-  `loginWithGoogle`, `loginWithGithub` ... -> login with an OAuth provider

Sorry for the long comment... What do you think?

**Comment by junekiwi** [comment]
Need to check the GraphQL spec. Maybe we can _overload_ the mutations with different arguments counts and type?

**Comment by junekiwi** [comment]
[https://stackoverflow.com/questions/40184367/do-graphql-fields-support-polymorphism-based-on-passed-in-arguments](https://stackoverflow.com/a/40189159)

> GraphQL fields can have optional arguments. So for example if you have a field called individuals, you could use optional arguments to supply different kinds of filters, for example: individuals(search: "Dan") or individuals(status: "admin"), or individuals (with no arguments) or individuals(status: "admin", search: "Dan") (both arguments provided at once.

Maybe we can do sth. like that and use `register`?

**Comment by jrebecchi** [comment]
Great idea!
